config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'hashtags/show/:name', to: 'hashtags#show'
  get '/users/hashtags/show', to: 'hashtags#show'
  resources :users
  resources :questions, except: %i[show new index]
  resource :session, only: %i[new create destroy]
end

app/models/question.rb
# :nodoc:
class Question < ApplicationRecord
  attr_accessor :namee #-invisible Captcha settings

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_and_belongs_to_many :hashtags, dependent: :destroy

  validates :text, :user, presence: true
  validates_length_of :text, minimum: 1, maximum: 255

  before_save :create_question_hashtags

  def create_question_hashtags
    hashtags.clear

    hashed_words = convert_words_into_hashtags

    hashed_words.each do |word|
      hashtags << Hashtag.find_or_create_by(name: word.delete('[]#""'))
    end
  end

  def convert_words_into_hashtags
    hashed_words = []

    text_array = text.split
    text_array += answer.split if answer

    text_array.each do |word|
      hashed_words << word.delete('#') if word =~ /\A#[\p{L}_]{1,30}\Z/
    end

    hashed_words.flatten
  end
end

app/controllers/questions_controller.rb
# :nodoc:
class QuestionsController < ApplicationController
  before_action :load_question, only: %i[:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]
  invisible_captcha honeypot: :namee, only: [:create, :update], on_spam: :spam_detected, timestamp_enabled: false

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  def create
    @question = Question.new(question_params)

    @question.author = current_user if current_user.present?

    @question.create_question_hashtags

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан.'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален.'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def load_question
    @question = Question.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer, :name)
    else
      params.require(:question).permit(:user_id, :text, :namee)
    end
  end

  def spam_detected
    redirect_to root_path, alert: 'Сработала спам-защита'
  end
end

app/helpers/questions_helper.rb
# :nodoc:
module QuestionsHelper
  def add_hashtags_to_text(hashwords, text)
    hashwords.each do |hashword|
      text.gsub!(/##{hashword}/) { link_to }
    end
    text
  end
end

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, t('views.questions.labels.question'), class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, t('views.questions.labels.answer'), class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= f.invisible_captcha :namee %> <%# invisible captcha helper %>

    <div class="form-action buffer-both">
      <%= f.submit t('views.questions.buttons.save'), class: 'button button-dark button-small' %>
      <% t('views.questions.labels.or') %>
      <%= link_to t('views.questions.buttons.back'), user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% text = question.text.split  %>
<% answer = question.answer.split unless question.answer.nil? %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= render partial: 'hashtags/text_with_hashtags', locals: {text: text, question: question} %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= render partial: 'hashtags/text_with_hashtags', locals: {text: answer, question: question} %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <div class="question-text">
      <% if question.author.present? %>
        <span class="text-small"> Автор</span>
        <%= link_to "@#{question.author.username}", user_path(question.author) %>
      <% else %>
        Аноним
      <% end %>
    </div>
  </div>

  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
      method: :delete, data: {confirm: t('views.questions.messages.confirm_deletion')}%>
    </div>
  <% end %>
</div>

app/views/questions/_question_w_hashtag.html.erb
<% question = question_w_hashtag%>
<% text = question.text.split  %>
<% answer = question.answer.split unless question.answer.nil? %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= render partial: 'hashtags/text_with_hashtags', locals: {text: text, question: question} %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= render partial: 'hashtags/text_with_hashtags', locals: {text: answer, question: question} %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <div class="question-text">
      <% if question.author.present? %>
        <span class="text-small"> Автор </span>
        <%= link_to "@#{question.author.username}", user_path(question.author) %>
      <% else %>
        Аноним
      <% end %>
    </div>

    <div class="question-text">
      <span class="text-small">Вопрос задан</span>
      <%= link_to "@#{question.user.username}", user_path(question.user) %>
    </div>

  </div>

  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: t('views.questions.messages.confirm_deletion')}%>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><% t('views.questions.buttons.question')%></h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>